############################################################
# +------------------------------------------------------+ #
# |                      Datebase                        | #
# +------------------------------------------------------+ #
############################################################
host: 0.0.0.0
port: 3306
database: mgtokens
username: mgtokens
password: secret